added some optional parameters/arguments/flags

diff --git a/awesomeshot b/awesomeshot
--- a/awesomeshot
+++ b/awesomeshot
@@ -229,7 +229,6 @@ function check() {
 }
 
 function autoRun() {
-  getUserConfig
   count=1
   header
   title "${COLOR_SKY}[?] WAITING TO TAKE SCREENSHOT${COLOR_DEFAULT}             [${COLOR_WARNING}${count}${COLOR_DEFAULT}]"
@@ -298,7 +297,6 @@ function autoRun() {
 }
 
 function manualRun() {
-  getUserConfig
   header
   title "${COLOR_SKY}[?] CHECKING FILE${COLOR_DEFAULT}"
   subtitle "[+]*Set*Status*File*"
@@ -550,33 +548,178 @@ function version() {
   echo -e "awesomeshot v.${version}"
 }
 
-while test $# -eq 0; then
+getUserConfig
+
+while test $# -gt 0; do
   case "${1}" in
     -a|--auto )
-      main autoRun
+      Mode="auto"
+      shift
     ;;
     -c|--config )
       generateDefaultConfig
+      shift $#
     ;;
     -m|--manual )
-      if [ ${2} ]; then
-        file_name="${2}"
-        main manualRun
+      shift
+      if test $# -gt 0; then
+        file_name=$1
+        Mode="manual"
       else
         echo ""
         stat "ERROR" "Danger" "This option require filename"
         help
         exit 1
       fi
+      shift
     ;;
     -h|--help )
       help
+      shift $#
     ;;
     -v|--version )
       version
+      shift $#
+    ;;
+    # optional parameter
+    -p|--png )
+      convert_to_png="yes"
+      shift
+    ;;
+    -P|--dont-png )
+      convert_to_png="no"
+      shift
+    ;;
+    -b|--backup )
+      shift
+      if test $# -gt 0; then
+        path_backup=$1
+        backup="yes"
+        shift
+      fi
+    ;;
+    -B|--dont-backup )
+      backup="no"
+      shift
+    ;;
+    -t|--titlebar )
+      shift
+      if test $# -gt 0; then
+        if [[ $1 == "--on-image" ]]; then
+          add_on_img="yes"
+          shift
+        else 
+          add_on_img="no"
+        fi
+        if [[ $1 == "--color" ]]; then
+          titlebar_color=$2
+          shift 2
+        fi
+        if [[ $1 == "--width" ]]; then
+          width_img=$2
+          shift 2
+        fi
+        if [[ $1 == "--height" ]]; then
+          height_img=$2
+          shift 2
+        fi
+      fi
+      convert_titlebar="yes"
+    ;;
+    -T|--disable-titlebar )
+      convert_titlebar="no"
+      shift
+    ;;
+    -r|--rounded )
+      shift
+      if test $# -gt 0; then
+        if [[ $1 == "--radius" ]]; then
+          border_radius=$2
+        fi
+      fi
+      convert_rounded="yes"
+    ;;
+    -R|--disable-rounded )
+      convert_rounded="no"
+      shift
+    ;;
+    -d|--border )
+      shift
+      if test $# -gt 0; then
+        if [[ $1 == "--color" ]]; then
+          border_color=$2
+          shift 2
+        fi
+        if [[ $1 == "--size" ]]; then
+          border_size=$2
+          shift 2
+        fi
+      fi
+      convert_border="yes"
+    ;;  
+    -D|--disable-border )
+      convert_border="no"
+      shift
+    ;;
+    -s|--shadow )
+      shift
+      if test $# -gt 0; then
+        if [[ $1 == "--color" ]]; then
+          shadow_color=$2
+          shift 2
+        fi
+      fi
+      convert_shadow="yes"
+    ;;
+    -S|--disable-shadow )
+      convert_shadow="no"
+      shift
+    ;;
+    -f|--footer )
+      shift
+      if test $# -gt 0; then
+        if [[ $1 == "--text" ]]; then
+          footer_text=$2
+          shift 2
+        fi
+        if [[ $1 == "--font" ]]; then
+          footer_font=$2
+          shift 2
+        fi
+        if [[ $1 == "--position" ]]; then
+          footer_position=$2
+          shift 2
+        fi
+        if [[ $1 == "--xy" ]]; then
+          footer_xy=$2
+          shift 2
+        fi
+        if [[ $1 == "--font-size" ]]; then
+          footer_font_size=$2
+          shift 2
+        fi
+        if [[ $1 == "--color" ]]; then
+          footer_foreground=$2
+          shift 2
+        fi
+        if [[ $1 == "--background" ]]; then
+          footer_background=$2
+          shift 2
+        fi
+      fi
     ;;
     *)
+      echo ""
+      stat "ERROR" "Danger" "\"${1}\" is invalid flags"
       help
+      shift $#
+      exit 1
     ;;
   esac
-done 
+done
+
+if [[ $Mode == "auto" ]]; then
+  main autoRun
+elif [[ $Mode == "manual" ]]; then
+  main manualRun
+fi
